### PR TITLE
Refactor animation controller methods and add generic action method ✅

### PR DESCRIPTION
**Pull request by kareemabdeen**
…to reduce code duplication and improve maintainability. Also added a new method to load the Rive file with its states for better organization.

### CODE REVIEW

**Comment by kareemabdeen** [comment]
please review and merge this into the codebase. I hope this is helpful. @omarahmedx14 ❤️

**Review by omarahmedx14 — APPROVED** [review]
Thank you.

**Comment by omarahmedx14** [comment]
please fix conflicts. @kareemabdeen

**Comment by kareemabdeen** [comment]
@omarahmedx14 ❤, Branch conflict solved and Ready to be merged

**Review by omarahmedx14 — APPROVED** [review]

**Pull request merged**
